### PR TITLE
Using babel-eslint as parser for esnext

### PR DESCRIPTION
**Pull request by joakimbeng**
Supporting [eslint-config-xo #3](https://github.com/sindresorhus/eslint-config-xo/pull/3).

I took the time to update `ava` and the dev `xo` as well...

### CODE REVIEW

**Comment by joakimbeng** [comment]
@sindresorhus have you had any time taking a look at this?

**Comment by sindresorhus** [comment]
Looks good. Thanks!

I'm working on finishing some other improvements. Will try to get out a new release in tomorrow.

**Comment by joakimbeng** [comment]
:+1:

**Comment by sindresorhus** [comment]
Alright. 0.8.0 is out! :)

**Comment by joakimbeng** [comment]
Thanks!

**Pull request merged**
